# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-21 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='rent',
            name='image',
            field=models.ImageField(default=0, upload_to=b'rents/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='rent',
            name='price',
            field=models.SmallIntegerField(default=0, help_text='\u0422', verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043c\u0435\u0441\u044f\u0446'),
        ),
    ]
