# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-21 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_auto_20190921_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='price',
            field=models.IntegerField(default=0, help_text='\u0422', verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043c\u0435\u0441\u044f\u0446'),
        ),
    ]
