# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-21 15:25
from __future__ import unicode_literals

import baseapp.mixins
from django.db import migrations, models
import django.db.models.deletion
import filesoup.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0003_auto_20190921_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=filesoup.helpers.upload_to_dir_rents)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rents.Rent')),
            ],
            bases=(baseapp.mixins.ImageModelMixin, models.Model),
        ),
    ]
