# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-26 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_clickhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_slogan',
            field=models.CharField(blank=True, default=b'', max_length=200, null=True, verbose_name='\u0421\u043b\u043e\u0433\u0430\u043d \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438'),
        ),
    ]
